services:
  # A Docker web service
  - type: web
    name: PiroAutoFilterBot
    env: python
    startCommand: python3 bot.py
    buildCommand: pip3 install -U -r requirements.txt
    repo: https://github.com/thealbinantony7/PiroAutoFilterBot.git # optional
    region: frankfurt # optional (defaults to frankfurt)
    plan: free # optional (defaults to starter)
    branch: master # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /

#End of yaml
